### ISSUE TITLE
question about results

### ISSUE THREAD

**Issue by MonsterLWR** [DeepTrial/Few-shot-Object-Detection-via-Feature-Reweighting#4]
hello, thanks for your effort to reformat the code. 
I have a question: did you get a similar results with the original paper? Is there something should be noted when reproducing the results in the paper? I tried several times, but I can not get a good results ...

**Comment by Fly-dream12** [comment]
I also encounter this problem. @MonsterLWR 
Can you leave your contact information for easier communication?

**Comment by MonsterLWR** [comment]
> I also encounter this problem. @MonsterLWR
> Can you leave your contact information for easier communication?

wechat:18987252842
